제목: 토큰 프론트 전달

diff --git a/.github/workflows/docker-image-main.yml b/.github/workflows/docker-image-main.yml
--- a/.github/workflows/docker-image-main.yml
+++ b/.github/workflows/docker-image-main.yml
@@ -3,7 +3,7 @@ name: Docker Image Build for Dev
 on:
   push:
     branches:
-      - dev
+      - main
 env:
   DOCKER_IMAGE_TAG_NAME: sesacsemi2-front
 
@@ -47,6 +47,26 @@ jobs:
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest
 
-      # 8. QEMU(Quick Emulator)를 설정
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
+      # 8. EC2에 배포
+      - name: Deploy to EC2
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.EC2_HOST }}
+          username: ${{ secrets.EC2_USER }}
+          key: ${{ secrets.EC2_KEY }}
+          script: |
+            echo "Pulling the latest Docker image..."
+            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest || exit 1
+
+            echo "Stopping and removing existing container..."
+            CONTAINER_ID=$(sudo docker ps -q --filter "publish=80-80")
+            if [ ! -z "$CONTAINER_ID" ]; then
+              sudo docker stop $CONTAINER_ID
+              sudo docker rm $CONTAINER_ID
+              sudo docker network prune -f 
+            fi
+            
+            sudo docker network prune -f || echo "Failed to prune networks"
+            sudo docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_TAG_NAME }}:latest
+
+            echo "Deployment completed successfully!"
